# Generated by Django 2.2.3 on 2019-08-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
            ],
            options={
                'verbose_name_plural': 'Клиенты',
                'verbose_name': 'клиента',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Вид', max_length=128, verbose_name='Название')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('link', models.CharField(default='url', max_length=128, verbose_name='Ссылка')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name_plural': 'Цены',
                'verbose_name': 'цену',
            },
        ),
    ]
