# Generated by Django 2.2.8 on 2020-01-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191023_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Комментарий'),
        ),
    ]
