# Generated by Django 2.2.11 on 2021-04-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool', models.BooleanField(default=True, verbose_name='Активность')),
                ('name', models.CharField(default='Услуга', max_length=128, verbose_name='Название')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'настройку сайта-каталога',
                'verbose_name_plural': 'Настройки Сайта-каталога',
                'ordering': ('id',),
            },
        ),
    ]
